name: website

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Depedencies
        run: npm install
      -
        name: Build App
        run: npm run dist
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload Build
        uses: actions/upload-artifact@v3.1.1
        with:
          name: WinBuild
          path: ./dist
