name: Build

on: push

jobs:
  publish:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Depedencies
        run: npm install
      -
        name: Build App
        run: npm run dist
        
      - name: Upload Build
        uses: actions/upload-artifact@v3.1.1
        with:
          name: WinBuild
          path: ./dist
